version: '3.8'

services:
  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - '8000:8000'
    volumes:
      - ./data:/data/db
    networks:
      - app_network

  logs-data:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - dynamodb
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
